#!/usr/bin/env bash

umask 002

chown root:root /home && chmod 775 /home

for dir in www bin; do
    [ ! -d "/home/$dir" ] && mkdir "/home/$dir"
done

[ -z "$CONF_PATH" ] && CONF_PATH="/home/conf"
[ ! -d "$CONF_PATH/supervisord" ] && mkdir -p "$CONF_PATH/supervisord"

BASHRC="/tmp/.bashrc"
[ ! -f "$BASHRC" ] && cat > $BASHRC << 'EOF'
# set a fancy prompt (non-color, unless we know we "want" color)
PS1='\[\033[01;34m\]\u\[\033[00m\]:\[\033[01;35m\]\w\[\033[00m\]\[\033[01;31m\] $ \[\033[00m\]'

# allow sudo to use completion from the current user's shell environment
complete -cf sudo

# some aliases
alias la='ls -AF'
alias LA='la'
alias ll='ls -lhAF'
alias LL='ll'
alias VIM='vim'
alias vi='vim'
alias VI='vim'
alias ENV='env'
alias c='clear'
alias sudo='sudo '
alias ..='. "$HOME/.rc"'
alias now='echo `date "+%Y-%m-%d %H:%M:%S %A"`'

# set bin PATH
PATH="$PATH:$HOME/bin:/home/bin"

# set conf PATH
CONF_PATH=$CONF_PATH

# source user's private .rc if exists
[ -f "$HOME/.rc" ] && . $HOME/.rc
EOF
chmod 666 $BASHRC

echo "[ -f \"$BASHRC\" ] && . $BASHRC" >> /root/.bashrc

cat > /etc/supervisor/supervisord.conf << EOF
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[include]
files = $CONF_PATH/supervisord/*.conf
EOF

if [ -z "$UNAME" ] || [ -z "$PASSWD" ]; then
    echo "root:password" | chpasswd

    cat > $CONF_PATH/supervisord/ttyd.conf << EOF
[program:ttyd]
stdout_logfile=/tmp/ttyd.log
redirect_stderr=true
autostart=true
autorestart=true
command=/usr/local/bin/ttyd -t enableTrzsz=true -c root:password -W bash
directory=/root
EOF
else
    echo "root:$PASSWD" | chpasswd

    if ! getent passwd $UNAME > /dev/null; then
        if [ ! -d "/home/$UNAME" ]; then
            useradd -m -s /bin/bash -G root,sudo $UNAME
        else
            useradd -M -s /bin/bash -G root,sudo $UNAME
        fi
        chmod 700 /home/$UNAME
        echo "$UNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$UNAME
        echo "$UNAME:$PASSWD" | chpasswd
        if [ ! -f "/home/$UNAME/.bashrc" ]; then
            echo "[ -f \"$BASHRC\" ] && . $BASHRC" > /home/$UNAME/.bashrc
        else
            grep -qF "[ -f \"$BASHRC\" ] && . $BASHRC" /home/$UNAME/.bashrc || echo "[ -f \"$BASHRC\" ] && . $BASHRC" >> /home/$UNAME/.bashrc
        fi
    fi

    if [ -n "$RSA" ]; then
        if [ ! -d "/home/$UNAME/.ssh" ]; then
            mkdir -p /home/$UNAME/.ssh
            chmod 700 /home/$UNAME/.ssh
            chown $UNAME:$UNAME /home/$UNAME/.ssh
        fi
        if [ ! -f "/home/$UNAME/.ssh/authorized_keys" ]; then
            touch /home/$UNAME/.ssh/authorized_keys
            chmod 600 /home/$UNAME/.ssh/authorized_keys
            chown $UNAME:$UNAME /home/$UNAME/.ssh/authorized_keys
        fi
        grep -qF "$RSA" /home/$UNAME/.ssh/authorized_keys || echo "$RSA" >> /home/$UNAME/.ssh/authorized_keys
    fi

    cat > $CONF_PATH/supervisord/ttyd.conf << EOF
[program:ttyd]
stdout_logfile=/tmp/ttyd.log
redirect_stderr=true
autostart=true
autorestart=true
command=/usr/local/bin/ttyd -t enableTrzsz=true -c $UNAME:$PASSWD -W bash
environment=HOME="/home/$UNAME",USER="$UNAME",LOGNAME="$UNAME"
directory=/home/$UNAME
user=$UNAME
EOF
fi

exec "$@"
