#!/usr/bin/env sh

if [ ! -f "/home/.bashrc" ]; then
    cat > /home/.bashrc << EOF
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=10000
HISTFILESIZE=20000

# set a fancy prompt (non-color, unless we know we "want" color)
PS1='\[\033[01;34m\]\u\[\033[00m\]:\[\033[01;35m\]\w\[\033[00m\]\[\033[01;31m\] \$ \[\033[00m\]'

# allow sudo to use completion from the current user's shell environment
complete -cf sudo

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more aliases
if [ -f /home/.bash_aliases ]; then
    . /home/.bash_aliases
fi
EOF
    chmod g+w /home/.bashrc
fi

if [ ! -f "/home/.bash_aliases" ]; then
    cat > /home/.bash_aliases << EOF
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'
EOF
    chmod g+w /home/.bash_aliases
fi

if [ ! -d "/home/bin" ]; then
    mkdir /home/bin
    chmod g+w /home/bin
fi

if [ ! -d "/home/conf" ]; then
    mkdir /home/conf
    chmod g+w /home/conf
fi

if [ ! -d "/home/supervisord.conf" ]; then
    mkdir /home/supervisord.conf
    chmod g+w /home/supervisord.conf
fi

cat > /etc/supervisor/supervisord.conf << EOF
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/tmp/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[include]
files = /home/supervisord.conf/*.conf
EOF

if [ -z "$USER" ] || [ -z "$PASSWD" ]; then
    USER="root"
    HOME="/root"
    TTYD_ARG="-t enableTrzsz=true"
else
    HOME="/home/$USER"
    TTYD_ARG="-t enableTrzsz=true -c $USER:$PASSWD"

    echo "root:$PASSWD" | chpasswd
    
    if ! getent passwd $USER >/dev/null; then
        useradd -s /bin/bash -d $HOME -G root,sudo $USER
        echo "$USER:$PASSWD" | chpasswd
        echo "$USER ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$USER
    fi

    if [ ! -d "$HOME" ]; then
        mkdir -p $HOME/.ssh
        chmod 700 $HOME/.ssh
        touch $HOME/.ssh/authorized_keys
        chmod 600 $HOME/.ssh/authorized_keys
        cat > $HOME/.bashrc << EOF
if [ -f /home/.bashrc ]; then
    . /home/.bashrc
fi
EOF
        chown $USER:$USER -R $HOME
    fi

    if [ -n "$RSA" ] && ! grep -qF "$RSA" $HOME/.ssh/authorized_keys; then
        echo "$RSA" >> $HOME/.ssh/authorized_keys
    fi
fi

cat > /home/supervisord.conf/ttyd.conf << EOF
[program:ttyd]
stdout_logfile=/tmp/ttyd.log
stderr_logfile=/tmp/ttyd.log
autostart=true
autorestart=true
command=/usr/bin/ttyd $TTYD_ARG -W bash
directory=$HOME
user=$USER
EOF

# 将环境变量加入/root/.bashrc
# env | sed -E '/^(_|PATH|USER|HOME|PWD|SHLVL|HOSTNAME|TERM|LOGNAME|RSA)=/d' | \
# while IFS= read -r line; do
#     if ! grep -qF "export ${line%%=*}" /root/.bashrc; then
#         echo "export $line" >> /root/.bashrc
#     fi
# done

exec "$@"
