#!/usr/bin/env bash

[ ! -f "/home/.bashrc" ] && cat > /home/.bashrc << EOF && chmod g+w /home/.bashrc
# set a fancy prompt (non-color, unless we know we "want" color)
PS1='\[\033[01;34m\]\u\[\033[00m\]:\[\033[01;35m\]\w\[\033[00m\]\[\033[01;31m\] $ \[\033[00m\]'

# allow sudo to use completion from the current user's shell environment
complete -cf sudo

# some aliases
alias sudo='sudo '
alias now='echo `date "+%Y-%m-%d %H:%M:%S %A"`'
EOF

for dir in bin conf supervisord; do
    [ ! -d "/home/$dir" ] && mkdir "/home/$dir" && chmod g+w "/home/$dir"
done

cat > /etc/supervisor/supervisord.conf << EOF
[unix_http_server]
file=/var/run/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
user=root
logfile=/tmp/supervisord.log
pidfile=/var/run/supervisord.pid
childlogdir=/tmp

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[include]
files = /home/supervisord/*.conf
EOF

if [ -z "$UNAME" ] || [ -z "$PASSWD" ]; then
    echo "root:password" | chpasswd

    cat > /home/supervisord/ttyd.conf << EOF
[program:ttyd]
stdout_logfile=/tmp/ttyd.log
stderr_logfile=/tmp/ttyd.log
autostart=true
autorestart=true
command=/usr/local/bin/ttyd -t enableTrzsz=true -c root:password -W bash
directory=/root
EOF
else
    echo "root:$PASSWD" | chpasswd

    if ! getent passwd $UNAME > /dev/null; then
        useradd -m -s /bin/bash -G root,sudo $UNAME
        echo "$UNAME ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/$UNAME
        echo "$UNAME:$PASSWD" | chpasswd
        echo '[ -f "/home/.bashrc" ] && . /home/.bashrc' >> /home/$UNAME/.bashrc
    fi

    if [ -n "$RSA" ]; then
        if [ ! -d "/home/$UNAME/.ssh" ]; then
            mkdir -p /home/$UNAME/.ssh
            chmod 700 /home/$UNAME/.ssh
            chown $UNAME:$UNAME /home/$UNAME/.ssh
        fi

        if [ ! -f "/home/$UNAME/.ssh/authorized_keys" ]; then
            touch /home/$UNAME/.ssh/authorized_keys
            chmod 600 /home/$UNAME/.ssh/authorized_keys
            chown $UNAME:$UNAME /home/$UNAME/.ssh/authorized_keys
        fi

        if ! grep -qF "$RSA" /home/$UNAME/.ssh/authorized_keys; then
            echo "$RSA" >> /home/$UNAME/.ssh/authorized_keys
        fi
    fi

    cat > /home/supervisord/ttyd.conf << EOF
[program:ttyd]
stdout_logfile=/tmp/ttyd.log
stderr_logfile=/tmp/ttyd.log
autostart=true
autorestart=true
environment=HOME="/home/$UNAME"
command=/usr/local/bin/ttyd -t enableTrzsz=true -c $UNAME:$PASSWD -W bash
directory=/home/$UNAME
user=$UNAME
EOF
fi

exec "$@"
